import Head from 'next/head';
import { Inter } from 'next/font/google';
import {BsMoonFill} from 'react-icons/bs';
import {BsSun} from 'react-icons/bs';
import { 
  AiFillLinkedin, 
  AiFillGithub,} from 'react-icons/ai';
import Image from 'next/image';
import avatar from 'public/avatar.jpg';
import htmllogo from 'public/html.png';
import csslogo from 'public/css.png';
import jslogo from 'public/js.png';
import reactlogo from 'public/react.png';
import tailwindlogo from 'public/tailwind.png';
import wordpresslogo from 'public/wordpress.png';
import web1 from 'public/web1.png';
import web2 from 'public/web2.png';
import web3 from 'public/web3.png';
import web4 from 'public/web4.png';
import web5 from 'public/web5.png';
import web6 from 'public/web6.png';
import {useState} from "react";


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jethendri Perera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px:40 dark:bg-neutral-900'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-mono dark:text-white'>JETHENDRI.PERERA</h1>
            <ul className=' flex items-center'>
              <BsSun className=' text-2xl text-white px-1'/>
              <label htmlFor="check" className=' bg-gray-100 relative w-16 h-8 rounded-full'>
                <input type="checkbox" id="check" onClick={() => setDarkMode(!darkMode)} className=' sr-only peer'/>
                <span className=' w-2/5 h-4/5 bg-rose-300 absolute rounded-full left-1 top-1 peer-checked:bg-rose-600 peer-checked:left-9 transition-all duration-500 '></span> 
              </label> 
              <BsMoonFill className=' text-2xl text-neutral-900 px-1 text-right'/>
              <li><a className=' bg-gradient-to-r from-red-600 to-rose-800 text-white px-4 py-2 rounded-md ml-8' href='https://www.linkedin.com/in/jethendri/'>LinkedIn</a></li>
            </ul>
          </nav>

          
            <div className='flex flex-wrap gap-9 text-center lg:py-10 lg:max-w-6xl md:justify-center sm:justify-center m-auto'>
              <div className='lg:text-left lg:px-20'>
                <h2 className=' text-5xl py-5 text-rose-700 font-medium md:text-6xl'>Jethendri Perera</h2>
                <h3 className=' text-2xl font-mono py-2 md:text-3xl dark:text-white'> SOFTWARE DEVELOPER AND DESIGNER.</h3>
                <p className=' text-lg py-5 leading-8 text-gray-800 md:text-xl max-w-xl  dark:text-white'>Hi!, I am passionate individual with great collaborative and adaptability skills.
                </p>
                <div className=' text-4xl flex lg:justify-start justify-center gap-16 py-3 text-gray-600 dark:text-white'>
                  <a href="https://www.linkedin.com/in/jethendri/" target="_blank"><AiFillLinkedin /></a>
                  <a href="https://github.com/jwpx" target="_blank"><AiFillGithub /></a>
                </div>
              </div>
              <div className=' rounded-full w-80 h-80 overflow-hidden mx-auto'>
              <Image src={avatar}></Image>
              </div>
            </div>
            <div className=' flex flex-wrap gap-10 lg:max-w-6xl lg:px-20 m-auto lg:py-4 py-12 justify-center lg:justify-start'>
              <div><h3 className=' text-xl text-rose-700 font-medium'>TECH STACK | </h3></div>
              <div className=' lg:w-8 lg:h-8 w-10 h-10'><Image src={htmllogo}></Image></div>
              <div className=' lg:w-8 lg:h-8 w-10 h-10'><Image src={csslogo}></Image></div>
              <div className=' lg:w-8 lg:h-8 w-10 h-10'><Image src={jslogo}></Image></div>
              <div className=' lg:w-8 lg:h-8 w-10 h-10'><Image src={tailwindlogo}></Image></div>
              <div className=' lg:w-8 lg:h-8 w-10 h-10'><Image src={reactlogo}></Image></div>
              <div className=' lg:w-8 lg:h-8 w-10 h-10'><Image src={wordpresslogo}></Image></div>
            </div>
        </section>

        <section>
          <div className='md:flex gap-10 lg:max-w-6xl m-auto py-20'>
          <div><h3 className=' text-2xl py-1 text-rose-700 font-medium'>BACKGROUND</h3></div>
          <div className=' text-lg text-justify leading-8 text-gray-800 dark:text-white'>
            <p className='py-2 '>
              I recently graduated from <span className=' text-rose-700 font-medium'>Victoria University - Australia</span> after completing Bachelor
              of Information Technology (Web and Mobile Application Development).
            </p>
            <p className='py-2'>
              As a web developer, I enjoy bridging the gap between engineering and design - 
              Combining my technical knowledge with my keen eye for design to create a beautiful product.
              My goal is to always build applications that are scalable and efficient while providing engaging, 
              pixel-perfect user experiences.
            </p>
            <p className=' py-2'>
            <span className=' text-rose-700 font-medium'>When I'm not in front of a computer screen, </span> 
              I'm probably drawing, reading books or playing video games.
            </p>
          </div>
          </div>
        </section>

        
        <section>
          <div className=' md:flex gap-x-16 lg:max-w-6xl m-auto py-20 lg:py-36'>
            <div><h3 className=' text-2xl py-1 text-rose-700 font-medium'>PORTFOLIO <span className=' text-white dark:text-neutral-900'>.  </span></h3></div>
            <p className=' text-lg text-justify leading-8 text-gray-800 dark:text-white py-2'>
              Each project is a <span className=' text-rose-700 font-medium'>unique</span> web development
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'}/>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
